### PR TITLE
Redesign whole website

### PR DESCRIPTION
**Pull request by Nitrrine**
Homepage
Alternatives Page

* Improves readability
* Improves user experience
* Removes Tailwind
* Populates nuxt.config file
* Uses SCSS

### CODE REVIEW

**Comment by blryface** [comment]
The current page looks fine, and is similar enough to what essential does. The redesign looks too big and doesn't work properly on mobile.

**Comment by Nitrrine** [comment]
Reopening, it works properly on mobile now, it removes tailwind replacing it with normal styles making it more easier to change styles, it also uses google-fonts to load fonts, that's why i've removed Inter from static loading. That's the reason why it looks big. While I agree with that current design looks fine I still think this redesign improve UI & UX.

**Review by KTrain5169 — APPROVED** [review]
Font can look a little weird at places but otherwise that's fine

Now to convert the info branch...

**Comment by KTrain5169** [comment]
btw I am not doing ANY code changes until I can have my editor and the site load side by side lol, StackBlitz just refuses to work properly even with uBO disabled :(

**Comment by KTrain5169** [comment]
that's... a lot of conflicts

**Comment by blryface** [comment]
why was this reopened? We don't need a redesign, and I feel like we only should consider doing so if Essential redesigns their site too

**Comment by blryface** [comment]
if you need fixes in UI and UX, you can just pixel to touch up the existing `beta Pridecraft/loop/custard/blurryface/notessential` code

**Comment by KTrain5169** [comment]
LOL that's a long list

**Pull request closed without merging**
