### PR TITLE
Various patches

### PR DESCRIPTION
**Pull request by KTrain5169**
* Capes mod is now in the Cosmetics section
+ Addition: In-Game Account Switcher (name should be self-explanatory)
- Change: Simple Discord RPC replaced by CraftPresence

### CODE REVIEW

**Comment by KTrain5169** [comment]
nice

**Comment by KTrain5169** [comment]
what is the problem tf

**Comment by KTrain5169** [comment]
ffs I give up what is the problem

**Comment by KTrain5169** [comment]
I figured it out 🎉

**Comment by KTrain5169** [comment]
@blryface

**Review by blryface — APPROVED** [review]
lgtm

**Pull request merged**
