### PR TITLE
add: content & code licenses

### PR DESCRIPTION
**Pull request by KTrain5169**
## Category

- [ ] Add mod to alternatives page
- [ ] Site changes
- [x] Chore/documentation updates

## Why did you do this?

As ZekeZ pointed out yesterday at the time of writing, NotEssential doesn't have a license. This particularly makes it hard for other projects if they want to use our website's information as they don't know what license they need to comply with.

Therefore, the proposal is as follows:
* The original text on the website (for example, mod descriptions excluding that one Cosmetica quote) is licensed under CC-BY-SA 4.0. This license allows others to use the text on our website, as long as they credit us and ensure that adaptations are also licensed under this license.
* The website code (that is, the code that powers the website) is licensed under GPL v3. This ensures that the website code can still be reused by anyone as long as they also follow the terms of GPL v3.

## BREAKING CHANGES

- [ ] Tick this box if you made changes that may or may not break site functionality.

## What issues (if any) would this resolve?

Resolves #x

## Checklist

- [ ] I have put clear & concise details about the mod onto the page.
- [ ] Links I have put in are all valid.
- [ ] Mods added are not RATs.

- [ ] I have clearly stated why I want this to be changed.
- [ ] For major changes, I have clearly stated what they are and why I've done them.
- [ ] Any new resources put in are safe and not malicious.

- [x] I have clearly explained why I have done this.
- [x] I have proofread the documentation changed and have ensured there are no spelling or grammatical errors.
- [ ] (Workflow updates only) I have tested the workflow to ensure its functionality.

- [ ] I have searched for duplicate PRs and have not found any.
- [ ] I did not read this section.

Vercel will begin deploying to the Preview environment shortly after submitting this pull request. You may click on the "Visit Preview" link below to see a preview of what your changes look like.
If you updated only part of the repository such that it would not modify the website at all, you do not need to see the Vercel deployment.

You may also use the StackBlitz Codeflow button to quickview the PR in the browser and make changes at the same time if necessary.

### CODE REVIEW

**Comment by KTrain5169** [comment]
how tf did that fail, it worked normal before and like, NOTHING CHANGED

**Review by Nitrrine — APPROVED** [review]

**Review by blryface — CHANGES_REQUESTED** [review]
Text license can't be CC BY-SA because that would make projects that want to use our content required to use CC BY-SA too (according to ZekeZ)

**Comment by Gaming32** [comment]
That is what the SA means, yes. CC BY would not include the ShareAlike clause. CC BY only requires attribution.

**Comment by KTrain5169** [comment]
Alright, I'm currently busy right now but as soon as I get home I'll change the license and push it, unless one of you guys can change it for me right now.

**Review by worldwidepixel — APPROVED** [review]
looks good?

**Review by blryface — APPROVED** [review]
lgtm

**Pull request merged**
