### PR TITLE
Populate nuxt.config.ts

### PR DESCRIPTION
**Pull request by Nitrrine**

### CODE REVIEW

**Review by blryface — CHANGES_REQUESTED** [review]
Why remove the `` | Not Essential``?

**Comment by Nitrrine** [comment]
> Why remove the `` | Not Essential``?

This line `titleTemplate: "%s | Not Essential",` will automatically add it

**Comment by blryface** [comment]
im stupid

**Review by blryface — APPROVED** [review]
:3

**Pull request merged**
